/* Generated from README by exspec.awk. */
static char *exspec_lines[] = {
	"EX PARSING",
	"Parsing follows the structure:",
	"[<sep>][prefix][cmd][<pad>][args]",
	"Ex commands are initiated and separated by <sep>. Fields can",
	"be padded by <Space> or <Tab>. [prefix] is a field consumed by",
	"[cmd], which accepts [range] structure characters. Padding inside",
	"[prefix] structure is collapsed, except within nested blocks.",
	"There can only be one pad in between [cmd] and [args]. To avoid",
	"ambiguity in scripts, it is recommended to always use a pad between",
	"[cmd] and [args].",
	"",
	"Examples:",
	"evi.c",
	"Evaluates to \"e vi.c\"",
	"efbc",
	"Evaluates to \"ef bc\" not \"e fbc\"",
	"e  vi.c",
	"Edit \" vi.c\". <pad> is required",
	"",
	"EX ESCAPES",
	"Special characters in [args] and [prefix] blocks will become",
	"regular when escaped with <\\>. Escapes are governed by a non-POSIX",
	"parity rule: escapes directly before a special are halved, an",
	"odd amount makes the special regular, and escapes anywhere else",
	"are literal.",
	"",
	"( ^ ] -",
	"Specials in regex \"[]\" expression",
	"( ) { + * \? ^ $ [ | \\ . \\< \\>",
	"Specials in regex",
	"\\ : % !",
	"Specials in ex",
	"",
	"EX EXPANSION",
	"<%> in [args] expands to current buffer pathname or any buffer",
	"pathname when followed by a corresponding buffer number.",
	"%# expands to last swapped buffer pathname.",
	"%@ expands to register specified.",
	"",
	"Example: make a copy of the current file and edit it",
	"!cp % %_:e %_",
	"Example: insert current buffer pathname",
	"&i%",
	"Example: echo the value of <a> register",
	"!echo %@97",
	"",
	"<!> in [args] starts and optionally ends a block containing",
	"external commands. This block executes and expands to stdout",
	"and stderr produced.",
	"",
	"Example: substitute \"int\" with the value of $RANDOM",
	"%s/int/!printf \"%s\" $RANDOM!",
	"Example: insert output of ls shell command",
	"&i!ls",
	"Example: insert output of ls more efficiently",
	";c!ls!<^V><ESC>",
	"",
	"EX RANGES",
	"Some ex commands can be prefixed with ranges.",
	"[range] prefix implements vertical and horizontal ranges.",
	"[vrange] prefix implements vertical range and horizontal position.",
	"Without [cmd], [vrange] replaces [prefix].",
	"",
	"[% |][, ;][#][. $ ' > <][- + * / %][#num]",
	"All ranges structure",
	"{|}{cmd}[|]",
	"Ex subcommand structure",
	"{>}[regex][>]",
	"Search forward structure",
	"{<}[regex][<]",
	"Search backward structure",
	"'{#mark}",
	"Mark structure",
	"",
	"%       Range from first to last line",
	"|       Begin ex subcommand block",
	",       Vertical range separator",
	";       Horizontal range separator",
	"#       Rebase to previous value in range structure",
	".       Current position",
	"$       Last line of a buffer or end of line",
	"'       Begin mark structure",
	">       Begin search forward block",
	"<       Begin search backward block",
	"-       Subtract following number",
	"+       Add following number",
	"*       Multiply by the following number",
	"/       Divide by the following number",
	"%       Modulo by the following number",
	"#num    Number or position",
	"",
	"Examples:",
	"1,5p   Print lines 1,5",
	".-5,.+5p",
	"Print 5 lines around current position",
	">int>p",
	"Print first occurrence of \"int\"",
	"<int<p",
	"Print first occurrence of \"int\" in reverse",
	".,>int>p",
	"Print until \"int\" is found",
	"<int<,.p",
	"Print until \"int\" is found in reverse",
	">      Search using previously set regex keyword",
	"'100,'97p",
	"Print lines from mark <d> to mark <a>",
	"%p     Print all lines in a buffer",
	"$p     Print last line in a buffer",
	"$*50/100+1",
	"Goto 50% of the file",
	";50    Goto character offset 50",
	"10;50  Goto line 10 character offset 50",
	"10;.+5",
	"Goto line 10 +5 character offset",
	"'97;'97",
	"Goto line mark <a> offset mark <a>",
	";$     Goto end of line",
	"5;>int>",
	"Search for \"int\" on line 5",
	".;<int<",
	"Search for \"int\" in reverse on the current line",
	";5;+10=",
	"+10 is relative to the initial current offset, not 5",
	";5;#+10=",
	"+10 is relative to 5",
	";>int>+3;#>>p",
	"Print text enclosed by \"int\" on the current line",
	"|grp1|;>(a)+>+1|grp|;#>>p",
	"Print text enclosed by a non-deterministic pattern \"a+\"",
	"",
	"EX COMMANDS",
	"[range]f>[regex]",
	"[vrange]f<[regex]",
	"Ranged search",
	"",
	"No argument uses previously set regex keyword.",
	"Returns error if target not found.",
	"If cursor is out of bounds, forward search pins to range start,",
	"backward search to range end.",
	"",
	"Example: no range given, current line only",
	"f>int",
	"Example: reverse",
	"f<int",
	"Example: range given",
	"10,100f>int",
	"",
	"[range]f+[regex]",
	"[vrange]f-[regex]",
	"Incrementing ranged search",
	"",
	"Equivalent to the f> and f< commands, except subsequent commands",
	"advance past match boundary. Cannot match inplace.",
	"",
	"[vrange]f[regex]",
	"Fuzzy search prompt",
	"",
	"Enters a fuzzy search prompt with a list of matches.",
	"Matches are prefixed by selection numbers and line numbers.",
	"Match can be selected using numbers 0-9 if there are less than",
	"10 matches.",
	"<^C> or <ESC> to abort.",
	"<^M> or <Enter> to input a selection number larger than 9.",
	"",
	"No range evaluates to <%> range.",
	"No range displays a maximum of xrows * 3 matches.",
	"",
	"[vrange]g[<Delim>][regex][<Delim>][cmd]",
	"Global command",
	"",
	"Execute an ex command on a range of lines that matches an",
	"enclosed regex.",
	"Returns error if no line matches the pattern or [cmd] fails.",
	"",
	"No range evaluates to <%> range or <.> range when nested.",
	"",
	"Example: remove all empty lines",
	"g/^$/d",
	"",
	"Example: print lines matching previously set regex keyword",
	"g//p",
	"",
	"Multiple ex commands can be chained in one global command.",
	"To chain commands, the ex separator <:> must be escaped once.",
	"",
	"Example: print and append lines matching \"int\" to register <a>",
	"g/int/p\\:ya+ 97",
	"",
	"It is possible to nest global commands inside of global commands.",
	"The first global command will not be executed on lines that",
	"were changed by a nested global command.",
	"",
	"Example: nested global command",
	"Append \"has a semicolon\" to all lines that contain \"int\" and",
	"end with <;>.",
	"g/int/g/;$/& A has a semicolon",
	"",
	"Example: extract/print data enclosed in \"()\"",
	"grp1:err4:g/./;0\\:;>(\\().+\\)>;#>.+(\\))>+1p:err1:grp",
	"",
	"[vrange]g![<Delim>][regex][<Delim>][cmd]",
	"Inverted global command",
	"",
	"[range]re[regex]",
	"Set regex keyword",
	"",
	"Range escapes its text and uses it as the regex.",
	"",
	"Example: set keyword to \"int\"",
	"re int",
	"Example: set keyword from lines 1 to 3",
	"1,3re",
	"",
	"[vrange]i[str]",
	"Enter ex insert mode",
	"",
	"[str] specifies initial input into the insertion buffer.",
	"[str] in raw ex mode is injected directly and bypasses the",
	"interactive mode.",
	"",
	"Example: insert \"hello\" in vi/ex",
	"i hello<^M><ESC>",
	"Example: insert \"hello\" in vi/ex trimming <Newline>",
	"i hello<^M><^M><Backspace>",
	"Example: discard changes in vi/ex",
	"i hello<^M><^C>",
	"Example: immediately insert \"hello\"",
	"i hello<^V><ESC>",
	"Example: insert \"hello\" before specified position",
	"-1i hello<^V><ESC>",
	"Example: insert \"hello\" before line 1 (special case)",
	"0i hello<^V><ESC>",
	"Example: insert \"hello\" in raw ex mode",
	"i hello",
	"Example: insert two lines in raw ex mode",
	"i hello<^M>world",
	"Example: insert \"hello\" in raw ex mode (interactive)",
	"i<^M>hello<^M>.<^M>",
	"",
	"[range]c[str]",
	"Enter ex change mode",
	"",
	"In combination with seq and lim ex options, this command is",
	"optimal for modifying very long lines.",
	"Max insertion buffer is ~1.33GB on a 32 bit build.",
	"Max addressable line is 2.0GB on a 32 bit build.",
	"",
	"Example: replace current line with \"hello\"",
	"c hello<^M><ESC>",
	"Example: replace lines 1-5 with \"hello\"",
	"1,5c hello<^M><ESC>",
	"Example: insert \"hello\" at current character offset",
	";c hello<^M><ESC>",
	"Example: insert \"hello\" at end of line",
	";$c hello<^M><ESC>",
	"Example: insert \"hello\" at line 5 and end of line",
	"5;$c hello<^M><ESC>",
	"Example: delete 5 characters from current position",
	";;+5c<^M><ESC>",
	"",
	"[range]d",
	"Delete line(s)",
	"",
	"Example: delete from current position to the start of the buffer",
	"1,.;0;d",
	"Example: delete from current position to the end of the buffer",
	".,$;;$d",
	"",
	"[vrange]j[any]",
	"Join line(s)",
	"",
	"Range of two or more lines joins exactly those lines.",
	"Any argument activates padding mode.",
	"Returns error if there is nothing to join.",
	"",
	"Example: join all lines",
	"%j",
	"Example: join all lines with space padding",
	"%j x",
	"",
	"[range]s[<Delim>][regex][<Delim>][str][<Delim>][<g>][<m>][<^>][#reg]",
	"Substitute",
	"",
	"Find and replace text in a range of lines that matches an",
	"enclosed regex with an enclosed replacement string.",
	"Returns error if no substitution is performed.",
	"",
	"Example: range scoping",
	"1,5;5;5s/term1/term2/",
	"",
	"Example: replace matching previously set regex keyword",
	"%s//term2/",
	"",
	"Substitution backreference in [str] inserts the text of matched",
	"group specified by \\# where # is a group number. Digits are",
	"consumed greedily up to the highest existing group, rest are",
	"literal.",
	"",
	"Example: substitution backreference",
	"this is an example text for subs and has int or void",
	"%s/(int)|(void)/pre\\0after",
	"this is an example text for subs and has preintafter or void",
	"%s/(int)|(void)/pre\\2after/g",
	"this is an example text for subs and has prepreafterafter or prevoidafter",
	"",
	"Example: global replacement with <g>",
	"%s/term1/term2/g",
	"",
	"Example: anchor ^ at every search with <^>, implies <g>",
	"aaa",
	"%s/^a/X/^",
	"XXX",
	"",
	"Example: multiline mode <m>",
	".,+1s/term1<^V><^M>term2/term3/m",
	"",
	"Example: edit register <a> inplace",
	"s/term1/term2/97g",
	"",
	"ud      Undo",
	"",
	"Returns error if there is nothing to undo.",
	"",
	"rd      Redo",
	"",
	"Returns error if there is nothing to redo.",
	"",
	"[range]p[str]",
	"Print line(s) from a buffer",
	"",
	"No range prints a line based on the value of left ex option.",
	"Argument prints the evaluated argument.",
	"",
	"Example: utilize character offset ranges",
	"1,10;5;5p",
	"Example: interleaved character offset ranges",
	"1;5,10;5p",
	"Example: print current line from offset 5 to 10",
	".;5;10p",
	"Example: print buffer pathname",
	"p %",
	"",
	"[range]=[<0-3 Any>][any]",
	"Print range numbers",
	"",
	"Argument 0-3 selects a specific number.",
	"Any non-<0-3> or extra argument bypasses the buffer range check.",
	"No argument prints all range numbers.",
	"",
	"Example: print current character offset only",
	";= 2",
	"Example: print value of mark <a>",
	"'97=",
	"Example: calculate 75 - 100",
	",75-100=1p",
	"",
	"=\?[any]",
	"Print last error",
	"",
	"Any argument forwards the error status.",
	"",
	"[range]m{#marks}",
	"Set line mark(s)",
	"",
	"Marks are ids separated by spaces, set alternating between start",
	"and end of the range.",
	"",
	"Example: store ranges in <a> and <s> for later reuse in f> command",
	">top>,#>bottom>m 97 115:'97,'115f>middle",
	"",
	"m![#marks]",
	"Unset line mark(s)",
	"",
	"No argument unsets all marks in the current buffer.",
	"",
	"[range]ya[#reg]",
	"Yank into a register",
	"",
	"No argument yanks into default register.",
	"",
	"Example: yank into <a> using ranges",
	"1,5;5;5ya 97",
	"",
	"[range]ya+[#reg]",
	"Yank and append to a register",
	"",
	"Example: append to register <1>",
	"ya+ 49",
	"",
	"ya![#reg]",
	"Free a register",
	"",
	"[range]pu[#reg][any][\\!{cmd}]",
	"Paste or pipe a register",
	"",
	"Example: paste <a> at line 1 character offset 5",
	"1;5pu 97",
	"Example: paste <a> before line 1 (special case)",
	"0pu 97",
	"Example: copy default register to X11 clipboard",
	"pu \\!xclip -selection clipboard",
	"Example: copy register <a> to X11 clipboard",
	"pu 97 \\!xclip -selection clipboard",
	"",
	"[#reg]reg[str]",
	"Print registers or put into a register",
	"",
	"Prefix selects a register and argument replaces its contents.",
	"Prefix with no argument reassigns the default register.",
	"",
	"Example: shift the printing position to view offscreen register parts",
	"1left:reg",
	"Example: put \"hello\" into register <1>",
	"49reg hello",
	"",
	"[#reg]reg+[str]",
	"Print registers or append to a register",
	"",
	"e[path]",
	"Open a file at a path",
	"",
	"No argument opens \"unnamed\" buffer.",
	"Files larger than 2.0GB are truncated on a 32 bit build.",
	"Line breaking happens until the first nul terminator or EOF.",
	"",
	"e![path]",
	"Force open a file at a path",
	"",
	"No argument re-reads the current buffer from the filesystem.",
	"",
	"[vrange]ef[regex]",
	"Open file using fuzzy search prompt",
	"",
	"Requires the b-2 buffer to have a directory listing backfilled.",
	"",
	"Example: backfill b-2 using fd command",
	"fd",
	"Example: backfill b-2 using find",
	"b-2:%!find .",
	"",
	"Prompt behavior is equivalent to the f command.",
	"",
	"Example: enter prompt & print entire listing",
	"ef",
	"Example: search for pathname containing \"v\"",
	"ef v",
	"",
	"[vrange]ef![regex]",
	"Forced version of ef command",
	"",
	"[range]r[path]",
	"[range]r[\\!{cmd}]",
	"Read a file or a pipe",
	"",
	"Range is computed on a target.",
	"No range evaluates to <%> range.",
	"No argument evaluates to current buffer path.",
	"",
	"Example: read a file",
	"r vi.c",
	"Example: pipe in all data",
	"r \\!ls",
	"Example: pipe in only lines 3,5",
	"3,5r \\!ls",
	"",
	"[range]w[path]",
	"[range]w[\\!{cmd}]",
	"Write a file or a pipe",
	"",
	"No range evaluates to <%> range.",
	"No argument evaluates to current buffer path.",
	"",
	"Example: write a file",
	"w vi.c",
	"Example: pipe out all data into less",
	"w \\!less",
	"Example: pipe out only first 10 lines",
	"1,10w \\!less",
	"",
	"[range]w![path]",
	"Force write a file",
	"",
	"[range]wq[path]",
	"[range]wq[\\!{cmd}]",
	"Write a file or a pipe and exit",
	"",
	"[range]wq![path]",
	"[range]wq![\\!{cmd}]",
	"Force write a file or a pipe and force quit",
	"",
	"[range]x[path]",
	"Write unsaved changes and exit",
	"",
	"[range]x![path]",
	"Force write unsaved changes and force quit",
	"",
	"[#lvl]q[0-255]",
	"Exit",
	"",
	"Prefix exits [#lvl] ex recursion levels.",
	"Argument specifies shell exit code.",
	"",
	"Example: conditionally exit this level and 1 above",
	"%f>marker:\?\?!p no marker\\:1q:s/old/new/g:w",
	"",
	"[#lvl]q![0-255]",
	"Force quit",
	"",
	"Prefix force quits [#lvl] recursion levels.",
	"No prefix quits all recursion levels.",
	"",
	"Example: set register <#0> to \"hello\" 3 levels deep, force quit",
	"this level and 2 above, print the register outside",
	"&Q&Q\\\\\\:&Q0reg hello\\\\\\\\\\\\\\:2q\\\\\\\\\\\\\\!:p %@0",
	"",
	"b[#index]",
	"Print buffers or switch to a buffer",
	"",
	"Temporary buffers are separate from the main buffers",
	"and are selected by a negative index.",
	"",
	"Example: switch to the 5th buffer",
	"b5",
	"Example: switch to the /hist/ ex history buffer",
	"b-1",
	"Example: switch to the /fm/ directory listing buffer",
	"b-2",
	"Example: switch to the /sc/ scratch buffer",
	"b-3",
	"Example: clear history and return to previous (#) main buffer",
	"b-1:%d:b-1",
	"",
	"bp[path]",
	"Set current buffer path",
	"",
	"bs[any]",
	"Set current buffer saved",
	"",
	"Argument resets undo/redo history",
	"",
	"bx[#]   Set max number of buffers allowed",
	"",
	"Buffers will be deallocated if the number specified is lower",
	"than the number of buffers currently in use.",
	"No argument resets to the default value of 10.",
	"",
	"cd[path]",
	"Set a working directory",
	"",
	"No argument relinks the current directory in case it got removed",
	"or unmounted.",
	"",
	"Currently open buffers' file paths will be automatically adjusted",
	"to reflect a newly set working directory.",
	"",
	"fp[path]",
	"Clear or set a secondary directory path",
	"",
	"fd[path]",
	"Calculate directory listing in b-2 buffer",
	"",
	"No argument uses secondary or a working directory path.",
	"",
	"inc[regex]",
	"Include regex for fd command calculation",
	"",
	"No argument disables the filter.",
	"",
	"Example: include only files in submodule directory that end with .c",
	"inc submodule.*\\.c$",
	"Example: exclude .git and submodule folders",
	"inc (^(\?\\:(\?\\!^\\.git|^submodule).)+[^/]+$)",
	"",
	"[range]![cmd]",
	"Run an external program",
	"",
	"When a range is specified, the buffer's data is piped to an external",
	"program. The resulting stdout and stderr are then piped back into the",
	"buffer, replacing the contents of the original range.",
	"No range returns an error if shell exit code is not zero.",
	"",
	"Example: infamously sort a buffer",
	"%!sort",
	"Example: replace \"int\" with \"uint\" using sed",
	"%!sed -e 's/int/uint/g'",
	"Example: pipe in result of ls command without line replacement",
	";$+1!ls",
	"Example: capitalize word at current position using tr",
	";;>\\\\\\>>!tr '[\\:lower\\:]' '[\\:upper\\:]'",
	"",
	"&{macro}",
	"Global non-blocking macro",
	"",
	"Execute raw vi input sequence.",
	"A non-blocking macro shall not wait for input when the end of",
	"the sequence is reached. A non-blocking macro executing other",
	"macros will always reach a terminating point.",
	"",
	"Example: execute vi insert statement",
	"& ihello",
	"Example: execute :hello",
	"& \\:hello<^V><^M>",
	"Example: execute vi \"ci(int\" macro",
	"& ci(int",
	"Example: nest blocking macro inside non-blocking",
	"& \\:@ \\\\\\:blocking<^V><^M>i continue in non-blocking",
	"Example: enable permanent vi line numbers",
	"& 2#",
	"",
	"@{macro}",
	"Global blocking macro",
	"",
	"Execute raw vi input sequence.",
	"A blocking macro shall wait for input when the end of the sequence",
	"is reached. A blocking macro executing other macros may cause",
	"input congestion.",
	"",
	"Example: execute vi insert statement",
	"@ ihello",
	"Example: insert \"hello\" into <:> vi prompt",
	"@ \\:hello",
	"Example: execute vi \"ci(int\" macro",
	"@ ci(int",
	"Example: execute \"ci(int\" exiting insert mode",
	"@ ci(int<^V><^C>",
	"Example: execute \"ci)INT\" as a follow-up",
	"@ ci(int<^V><^C>ci)INT",
	"Example: execute vi \"dw\" command after user exits insert",
	"@i:@dw",
	"",
	"[#count <$>]\?[cond]",
	"While loop",
	"",
	"Repeat [cond] [#count] times or infinite with [<$>].",
	"While loop is broken once [cond] returns an error or count exceeded.",
	"Error status of [cond] is forwarded.",
	"No prefix defaults [#count] to 1.",
	"",
	"Example: attempt to join every line in file using arbitrary count",
	"10000\? & J",
	"Example: undo everything",
	"$\? ud",
	"Example: repeat chain of ex commands 10 times",
	"10\? 1p\\:5p\\:10p",
	"",
	"[#count <$>]\?![cond]",
	"Inverted while loop",
	"",
	"[prefix]\?\?[then]",
	"{prefix}\?\?",
	"Conditional",
	"",
	"Branching depends on the error status of the last command.",
	"Error status of [then] is forwarded.",
	"No prefix and no argument forwards the last error status.",
	"",
	"A prefix without arguments captures the current error status",
	"at that point in a command chain into capture id specified.",
	"Capture ids are global across all nested command contexts.",
	"",
	"A prefix with arguments branches based on the boolean expression",
	"in DNF over the most recent captures of each referenced id.",
	"If id has no capture, the branch is skipped.",
	"",
	"Prefix operators:",
	"Numerical capture id",
	", AND (higher precedence)",
	"; OR (lower precedence)",
	"",
	"Example: calculate directory only if cd command succeeded",
	"cd /blah:\?\? fd",
	"Example: print a line only if it contains \"int\" at offset 5",
	";5;#>^int>:\?\? p",
	"Example: edit vi.c only if it exists",
	"![ -f ./vi.c ]:\?\?e ./vi.c:mpt1",
	"Example: capture error status at id 5, branch later",
	">int>:5\?\?:;=:5\?\?p",
	"Example: skip if id was never set",
	"2\?\?.=",
	"Example: AND -- branch only if both ids captured success",
	"f>int:1\?\?:f>void:2\?\?:1,2\?\?p found both",
	"Example: OR -- branch if either id captured success",
	"f>int:1\?\?:f>void:2\?\?:1;2\?\?p found one",
	"Example: DNF -- (1 AND 2) OR (3 AND 4)",
	"1,2;3,4\?\?p then",
	"",
	"[prefix]\?\?![then]",
	"{prefix}\?\?!",
	"Inverted conditional",
	"",
	"Example: inverted capture",
	"f>int:1\?\?!:1\?\?p int was absent",
	"",
	"{prefix}\?\?\?",
	"Evaluate capture ids",
	"",
	"This is a nop command that evaluates a boolean expression",
	"at prefix and returns the result.",
	"",
	"Example: control while loop",
	"$\? \\%f+int\\:1\?\?\\:\\%f+void\\:2\?\?\\:1,2\?\?p\\:1,2\?\?\?",
	"",
	"[#id]\?~[any]",
	"Control capture ids lifetime",
	"",
	"Prefix selects a specific id to free.",
	"No argument and no prefix frees all captured error statuses.",
	"Argument toggles capture status preservation across",
	"separate ex command chains.",
	"",
	"Example: id 2 capture leaks into unrelated code",
	"f>int:2\?\?:f>zzz:1\?\?:1\?\?f>int\\:2\?\?:2\?\?p LEAKED",
	"Example: prevent id 2 leak",
	"f>int:2\?\?:2\?~:f>zzz:1\?\?:1\?\?f>int\\:2\?\?:2\?\?p LEAKED",
	"",
	"Example: use a capture at the next <:> prompt",
	"\?~x:![ -f ./vi.c ]:1\?\?",
	"1\?\?p vi.c exists",
	"",
	"ft[filetype]",
	"Set a filetype",
	"",
	"No argument prints the current file type.",
	"Reloads the highlight ft, which makes it possible to reset dynamic",
	"highlights created by options like \"hlw\".",
	"",
	"cm[keymap]",
	"Set a keymap",
	"",
	"No argument prints the current keymap name.",
	"",
	"cm![keymap]",
	"Set an alternative keymap",
	"",
	"exspec[command range topic]",
	"Print ex command catalog or specification",
	"",
	"No argument lists useful commands for agents, the full catalog for",
	"humans. Use catalog for all commands and options; use a command name",
	"for its specification, including hidden commands. Topics: parsing,",
	"escapes, expansion, ranges, regex, commands, options.",
	"",
	"Example: list all commands",
	"exspec catalog",
	"",
	"[range]a[text]",
	"Open or resume the agent conversation",
	"",
	"Keeps the conversation. Text prefills the prompt; range attaches",
	"buffer text to the next submission. Enter adds a newline; Escape",
	"submits; Ctrl-C exits; Ctrl-O opens the editor. Ex specials are",
	"disabled. Unavailable as an agent tool.",
	"",
	"[range]a![text]",
	"Start a new agent conversation",
	"",
	"Clears history and log, aspec tracking and deferred command.",
	"Range, text and prompt controls work as for a. Unavailable as an agent tool.",
	"",
	"[range]a~[text]",
	"Resume an agent conversation from its log",
	"",
	"Loads b-4 as context, including edits. Keeps aspec tracking.",
	"Range, text and prompt controls work as for a. Unavailable as an agent tool.",
	"",
	"[range]apack[text]",
	"Compact the agent session from its log",
	"",
	"Loads b-4 as context and asks the agent to replace it with a summary.",
	"Stays at the prompt; reloads the log on exit. Text replaces the default",
	"instructions; range attaches buffer text. Unavailable as an agent tool.",
	"",
	"[range]apack![text]",
	"Compact the agent session by browsing its log",
	"",
	"Starts fresh without loading or clearing b-4. The agent reads bounded",
	"ranges and replaces the log with a summary. Stays at the prompt;",
	"reloads on exit. Resets aspec tracking. Text and range work as for",
	"apack. Unavailable as an agent tool.",
	"",
	"acm",
	"Toggle the caveman response style skill",
	"",
	"Adds or removes the skill in b-5. Tool calls update the system",
	"message; otherwise context is rebuilt from the log.",
	"",
	"aretry",
	"Execute the last deferred agent command once",
	"",
	"Uses the saved range and expanded argument. Takes no range or",
	"argument. A new deferral replaces it; retry consumes it even on",
	"failure. A new session clears it. Errors if none is saved.",
	"",
	"Example: execute a deferred command",
	"aretry",
	"",
	"ast",
	"Print agent status and token usage",
	"",
	"Prints sizes, per-role usage, activity, limits and autocompact mode.",
	"Usage counts come from the last accepted response. Next input is",
	"estimated from reported input plus new JSON bytes / 3, or all JSON",
	"bytes / 3 without a usable count. Includes tool definitions and",
	"framing; not a tokenizer or a guarantee the request fits.",
	"",
	"ac[regex]",
	"Set autocomplete filter regex",
	"",
	"No argument resets to the default word filter regex as defined",
	"in led.c.",
	"",
	"Example: autocomplete using whole lines from a buffer",
	"ac .+",
	"",
	"[<0-3>]sc[<esc>][<sep>][<exp>][<exe>]",
	"Set ex special characters",
	"",
	"Prefix selects a specific character to change.",
	"Missing arguments default to <\\ : % !>.",
	"",
	"Example: change <%> to <a>",
	"2sc a",
	"Example: utilize newly set separator in a single command chain",
	"|1sc a|: p cmd1 a p cmd2 a|sc|a0\?:p cmd3",
	"",
	"[<0-3>]sc![<esc>][<sep>][<exp>][<exe>]",
	"Set ex special characters",
	"",
	"Missing arguments default to <#0>.",
	"",
	"Example: disable <exp> and <exe>",
	"sc! \\\\\\:",
	"",
	"uc      Toggle multi-byte UTF-8 decoding",
	"",
	"This command is particularly useful when editing files with",
	"mixed encodings, binary files, or when the terminal does not",
	"support UTF-8 or lacks the necessary fonts to display UTF-8",
	"characters. It is often paired with ph command to achieve",
	"hex editor-like functionality.",
	"",
	"uz      Toggle zero-width character placeholders",
	"",
	"Hides zero-width characters rather than rendering them as placeholders.",
	"",
	"ub      Toggle multi-codepoint sequence placeholders",
	"",
	"Passes multi-codepoint sequences such as emojis to the terminal",
	"for native rendering rather than substituting placeholders.",
	"",
	"ph[#clow] [#chigh] [#width] [#blen][<Space>][str]",
	"Redefine placeholders",
	"",
	"This command replaces placeholders defined in conf.c",
	"and subsequent ph commands expand the list of placeholders.",
	"",
	"Example: render 8 bit ascii (Extended ASCII) as <~>",
	"ph 128 255 1 1~",
	"Example: flawless ISO/IEC 8859-1 (latin-1) support",
	"uc:ph 128 160 1 1~",
	"Example: render control byte 03 as \"^C\"",
	"ph 3 3 2 1^C",
	"Example: reset to default as in conf.c",
	"ph",
	"Example: disable default placeholders in conf.c",
	"ph:ph0",
	"",
	"EX OPTIONS",
	"Ex options are ex commands designed to alter global variables.",
	"Variables hold a signed integer. Argument sets the value. A non-numeric",
	"argument yields its first byte. No argument logically inverts",
	"the current value, unless stated otherwise.",
	"",
	"Argument notation shows the default value.",
	"",
	"aco[0]  Automatically compact using the loaded session log",
	"Positive argument sets an estimated input-token threshold; 0 or",
	"negative disables. No argument enables at 85000 or toggles off.",
	"aco and aco! share a threshold; the last setting wins.",
	"",
	"After tool batches, runs apack without a prompt and resumes. Never",
	"recurses. Failed, cancelled or inadequate summaries keep the old",
	"history and stop the run. Leave room for instructions and output;",
	"use aco! if the log cannot fit. Does not change the API limit.",
	"",
	"aco![0]  Automatically compact by browsing the session log",
	"Threshold and toggle work as for aco (default 85000). Selecting",
	"either mode replaces the other.",
	"",
	"Runs apack! with fresh context and bounded reads of b-4. Keeps the",
	"current task and restores the editor buffer. Use ast for status",
	"and token estimates.",
	"",
	"ar[0]  Display returned agent reasoning",
	"No argument logically inverts the option.",
	"",
	"Nonzero includes returned reasoning in the session log.",
	"",
	"gr[2]  Control agent output protection",
	"No argument logically inverts the option.",
	"",
	"Value 2 limits tool output to 4096 bytes and protects captured shell",
	"output. Other values disable protection; 0 and 1 increment after",
	"each tool call until 2. Negative values stay disabled.",
	"",
	"aspec[1]  Print ex specifications for agents",
	"",
	"No argument logically inverts the option. 0 disables automatic",
	"specifications; 1 enables them (the default).",
	"",
	"ai[1]   Indent new lines",
	"",
	"This is a max indent length multiplier: value * 128",
	"",
	"ic[1]   Ignore case in regular expressions",
	"",
	"ish[0]  Interactive shell",
	"",
	"Run every <!> command through an interactive shell.",
	"The shell will source the .rc file before command execution.",
	"This makes it possible to use predefined functions, aliases",
	"and ENV variables from the .rc file.",
	"Precondition 1:",
	".rc refers to a shell-specific filename, such as .bashrc",
	"in Bash or .zshrc in Zsh.",
	"Precondition 2:",
	"The environment variable $SHELL determines the default",
	"shell, otherwise it defaults to /bin/sh.",
	"Precondition 3:",
	"There must be no stdout or stderr output created by .rc",
	"file for <!> commands to return expected results.",
	"",
	"grp[0]  Regex search group",
	"",
	"Defines a target search group for any regex search operation.",
	"This becomes necessary when the result of a regex search is to",
	"be based on some group rather than the default match group.",
	"",
	"Example: position on a character prefixed by \"int\"",
	"grp 1:%f+int(.):grp",
	"",
	"hl[1]   Highlight text based on rules defined in conf.c",
	"",
	"Value greater than 1 highlights using C extensions only.",
	"",
	"hlr[0]  Highlight text in reverse direction",
	"hll[0]  Highlight current line based on filetype hl",
	"hlp[0]  Highlight \"[]\" \"()\" \"{}\" pairs based on filetype hl",
	"hlw[0]  Highlight current word based on filetype hl",
	"led[1]  Enable all terminal output",
	"",
	"vis[0]  Control startup flags",
	"",
	"bit 1: raw ex mode",
	"bit 2: ex mode",
	"bit 3: disable e command message",
	"bit 4: alternate terminal screen",
	"",
	"Example: enable raw ex mode",
	"vis 3",
	"Example: disable raw ex mode",
	"vis 2",
	"",
	"mpt[0]  Control vi prompts",
	"",
	"When set to 0 or 1 after an ex command is called from vi, disables",
	"the \"[any key to continue]\" prompt.",
	"If mpt is negative, the prompt will remain disabled.",
	"",
	"Example: disable the prompt and the last print",
	"p:p:p:mpt 0",
	"Example: disable the prompt but not the last print",
	"p:p:p:mpt 1",
	"",
	"order[1]",
	"Reorder characters based on rules defined in conf.c",
	"shape[1]",
	"Perform Arabic script letter shaping",
	"pac[0]  Print autocomplete suggestions on the fly",
	"ts[8]   Number of spaces used to represent a tab",
	"td[1]   Current text direction context",
	"",
	"value  2: exclusively left-to-right",
	"value  1: follow dctxs[] in conf.c, default left-to-right",
	"value -1: follow dctxs[] in conf.c, default right-to-left",
	"value -2: exclusively right-to-left",
	"",
	"pr[0]   Print register",
	"",
	"Set a special register with a character or a number.",
	"Once the register is set, all ex printed output will",
	"be stored in the register.",
	"",
	"If the register is uppercase, <Newline> characters are added",
	"to match the exact output that was printed.",
	"",
	"Print register contents cannot be displayed with R or reg command",
	"when register is assigned (self-referential problem).",
	"",
	"Example: paste current buffer list exactly like from b command",
	"pr A:ya! 65: b:pu 65",
	"Example: store a line printed with p command",
	"pr A:ya! 65:p",
	"",
	"fr[0]   Find register",
	"",
	"Set a register with a character or a number.",
	"Once the register is set, the f> and f+ commands perform a",
	"multi-line search forward on the contents of the register instead",
	"of the current buffer. Range maps the match to a position in",
	"the current buffer. No range tests the match inplace.",
	"",
	"Example: search register <a> for \"int\"",
	"fr a:f>int:\?\?p yes:\?\?!p no:fr",
	"Example: search for \"int\" followed by \"void\" on next line",
	"%ya97:fr 97:%f>int.void:fr",
	"",
	"rr[0]   Record register",
	"",
	"Set a register with a character or a number.",
	"Once the register is set, every byte read from the terminal is",
	"appended to the register. Input replayed from registers is not",
	"recorded.",
	"",
	"Example: record keystrokes into register <a>",
	"rr a",
	"Example: stop recording",
	"rr",
	"Example: replay recording from register <a>",
	"& %@97",
	"",
	"lim[-1]",
	"Line length render limit",
	"",
	"Set render cutoff length for non cursor lines in vi and all",
	"lines in ex mode.",
	"",
	"Improves redraw performance when editing a file containing one",
	"or many long lines (1MB+ per line).",
	"",
	"Example: reasonable value",
	"lim 5000",
	"Example: render only the cursor line",
	"lim 0",
	"Example: disable the limit",
	"lim -1",
	"",
	"seq[1]  Control Undo/Redo",
	"",
	"When seq is 0, multiple distinct operations undo/redo in a",
	"single step.",
	"",
	"To optimize memory usage under heavy workloads, undo/redo",
	"tracking can be disabled by setting seq to a negative value.",
	"",
	"Example: test undo/redo operations in a single step",
	"&ocontrol test:seq 0:&a step1:&a step2:&a step3:seq",
	"Example: completely disable undo/redo",
	"seq -1",
	"",
	"[hscroll]left[0]",
	"Control horizontal scroll",
	"",
	"No argument calculates the value using current character offset.",
	"hscroll computes the value using: xcols / 2 * hscroll",
	"",
	"err[1]  Control ex errors",
	"",
	"bit 1: print errors",
	"bit 2: early return",
	"bit 3: ignore errors",
	"",
	"Example: silence and ignore errors",
	"err 4",
	"Example: report and return on first error",
	"err 3",
	"Example: report and consider only last command for error status",
	"err 1",
	"",
	"EX REGEX",
	"Pikevm is a fast non-backtracking NFA simulation regex engine",
	"developed for Nextvi. It ensures regular expressions are evaluated",
	"in constant space and O(n * k) time complexity where <n> is",
	"the input string length and <k> represents the regex's structural",
	"complexity (e.g., state transitions or alternations). While",
	"this does not guarantee strict O(n) linear runtime performance,",
	"it ensures computational and memory resources are distributed",
	"linearly and evenly across the input, with <k> directly influencing",
	"the constant factor. This principle is similar to the concept",
	"utilized in radix sort algorithms.",
	"",
	"Pikevm's syntax is akin to regexp(7) from Plan 9.",
	"Disregard manpage notation in this section.",
	"",
	".       Match any single character",
	"[N-M]   Match a set of alternate ranges N to M",
	"{N,M}   Match N to M times",
	"()      Capture grouping",
	"(\?:)    Non capture grouping",
	"*       Repeated zero or more times",
	"+       Repeated one or more times",
	"|       Union, alternative branch",
	"\?       One or zero matches greedy",
	"\?\?      One or zero matches lazy",
	"^       Assert start of line",
	"$       Assert end of line",
	"\\<      Assert start of word",
	"\\>      Assert end of word",
	"(\?=)    Assert positive lookahead",
	"(\?!)    Assert negative lookahead",
	"(\?>)    Assert positive lookbehind",
	"(\?<)    Assert negative lookbehind",
	"(\?#)    Lookbehind offset in bytes",
	"",
	"Lookaround expressions enable the creation of regular expressions",
	"that would be impossible to construct without them. They can",
	"be used anywhere within a regex, though some considerations",
	"must be taken into account.",
	"Aspect 1:",
	"Lookarounds contain a full regular expression.",
	"Aspect 2:",
	"Lookarounds can have nested lookarounds.",
	"Aspect 3:",
	"Static lookarounds like (\?=^word) are optimized, bypassing",
	"the regex engine.",
	"Aspect 4:",
	"Lookarounds are best suited for asserting near the end of a",
	"complex pattern, where the engine has already narrowed down",
	"potential matches.",
	"Aspect 5:",
	"Lookbehind without offset or 0 offset begins at previous character.",
	"Offset begins scanning from current position minus specified",
	"value. Negative offset begins at the start of the string.",
	"",
};
static struct {
	char *name, *desc;
	s64 begin, end, option, read;
} exspec_cmds[] = {
	{"f>", "Ranged search", 131, 146, 0, 0},
	{"f<", "Ranged search", 131, 146, 0, 0},
	{"f+", "Incrementing ranged search", 147, 153, 0, 0},
	{"f-", "Incrementing ranged search", 147, 153, 0, 0},
	{"f", "Fuzzy search prompt", 154, 166, 0, 0},
	{"g", "Global command", 167, 199, 0, 0},
	{"g!", "Inverted global command", 200, 202, 0, 0},
	{"re", "Set regex keyword", 203, 212, 0, 0},
	{"i", "Enter ex insert mode", 213, 238, 0, 0},
	{"c", "Enter ex change mode", 239, 259, 0, 0},
	{"d", "Delete line(s)", 260, 267, 0, 0},
	{"j", "Join line(s)", 268, 279, 0, 0},
	{"s", "Substitute", 280, 318, 0, 0},
	{"ud", "Undo", 319, 322, 0, 0},
	{"rd", "Redo", 323, 326, 0, 0},
	{"p", "Print line(s) from a buffer", 327, 341, 0, 0},
	{"=", "Print range numbers", 342, 355, 0, 0},
	{"=\?", "Print last error", 356, 360, 0, 0},
	{"m", "Set line mark(s)", 361, 369, 0, 0},
	{"m!", "Unset line mark(s)", 370, 374, 0, 0},
	{"ya", "Yank into a register", 375, 382, 0, 0},
	{"ya+", "Yank and append to a register", 383, 388, 0, 0},
	{"ya!", "Free a register", 389, 391, 0, 0},
	{"pu", "Paste or pipe a register", 392, 403, 0, 0},
	{"reg", "Print registers or put into a register", 404, 414, 0, 0},
	{"reg+", "Print registers or append to a register", 415, 417, 0, 0},
	{"e", "Open a file at a path", 418, 424, 0, 0},
	{"e!", "Force open a file at a path", 425, 429, 0, 0},
	{"ef", "Open file using fuzzy search prompt", 430, 446, 0, 0},
	{"ef!", "Forced version of ef command", 447, 449, 0, 0},
	{"r", "Read a file or a pipe", 450, 464, 0, 0},
	{"w", "Write a file or a pipe", 465, 478, 0, 0},
	{"w!", "Force write a file", 479, 481, 0, 0},
	{"wq", "Write a file or a pipe and exit", 482, 485, 0, 0},
	{"wq!", "Force write a file or a pipe and force quit", 486, 489, 0, 0},
	{"x", "Write unsaved changes and exit", 490, 492, 0, 0},
	{"x!", "Force write unsaved changes and force quit", 493, 495, 0, 0},
	{"q", "Exit", 496, 504, 0, 0},
	{"q!", "Force quit", 505, 514, 0, 0},
	{"b", "Print buffers or switch to a buffer", 515, 531, 0, 0},
	{"bp", "Set current buffer path", 532, 534, 0, 0},
	{"bs", "Set current buffer saved", 535, 539, 0, 0},
	{"bx", "Set max number of buffers allowed", 540, 545, 0, 0},
	{"cd", "Set a working directory", 546, 554, 0, 0},
	{"fp", "Clear or set a secondary directory path", 555, 557, 0, 0},
	{"fd", "Calculate directory listing in b-2 buffer", 558, 562, 0, 0},
	{"inc", "Include regex for fd command calculation", 563, 572, 0, 0},
	{"!", "Run an external program", 573, 589, 0, 0},
	{"&", "Global non-blocking macro", 590, 608, 0, 0},
	{"@", "Global blocking macro", 609, 629, 0, 0},
	{"\?", "While loop", 630, 644, 0, 0},
	{"\?!", "Inverted while loop", 645, 647, 0, 0},
	{"\?\?", "Conditional", 648, 685, 0, 0},
	{"\?\?!", "Inverted conditional", 686, 692, 0, 0},
	{"\?\?\?", "Evaluate capture ids", 693, 701, 0, 0},
	{"\?~", "Control capture ids lifetime", 702, 718, 0, 0},
	{"ft", "Set a filetype", 719, 725, 0, 0},
	{"cm", "Set a keymap", 726, 730, 0, 0},
	{"cm!", "Set an alternative keymap", 731, 733, 0, 0},
	{"exspec", "Print ex command catalog or specification", 734, 744, 0, 0},
	{"a", "Open or resume the agent conversation", 745, 752, 0, 0},
	{"a!", "Start a new agent conversation", 753, 758, 0, 0},
	{"a~", "Resume an agent conversation from its log", 759, 764, 0, 0},
	{"apack", "Compact the agent session from its log", 765, 771, 0, 0},
	{"apack!", "Compact the agent session by browsing its log", 772, 779, 0, 0},
	{"acm", "Toggle the caveman response style skill", 780, 785, 0, 0},
	{"aretry", "Execute the last deferred agent command once", 786, 795, 0, 0},
	{"ast", "Print agent status and token usage", 796, 804, 0, 0},
	{"ac", "Set autocomplete filter regex", 805, 813, 0, 0},
	{"sc", "Set ex special characters", 814, 824, 0, 0},
	{"sc!", "Set ex special characters", 825, 832, 0, 0},
	{"uc", "Toggle multi-byte UTF-8 decoding", 833, 840, 0, 0},
	{"uz", "Toggle zero-width character placeholders", 841, 844, 0, 0},
	{"ub", "Toggle multi-codepoint sequence placeholders", 845, 849, 0, 0},
	{"ph", "Redefine placeholders", 850, 866, 0, 0},
	{"aco", "Automatically compact using the loaded session log", 875, 884, 1, 0},
	{"aco!", "Automatically compact by browsing the session log", 885, 892, 1, 0},
	{"ar", "Display returned agent reasoning", 893, 897, 1, 0},
	{"gr", "Control agent output protection", 898, 904, 1, 0},
	{"aspec", "Print ex specifications for agents", 905, 909, 1, 0},
	{"ai", "Indent new lines", 910, 913, 1, 0},
	{"ic", "Ignore case in regular expressions", 914, 915, 1, 0},
	{"ish", "Interactive shell", 916, 931, 1, 0},
	{"grp", "Regex search group", 932, 940, 1, 0},
	{"hl", "Highlight text based on rules defined in conf.c", 941, 944, 1, 0},
	{"hlr", "Highlight text in reverse direction", 945, 946, 1, 0},
	{"hll", "Highlight current line based on filetype hl", 946, 947, 1, 0},
	{"hlp", "Highlight \"[]\" \"()\" \"{}\" pairs based on filetype hl", 947, 948, 1, 0},
	{"hlw", "Highlight current word based on filetype hl", 948, 949, 1, 0},
	{"led", "Enable all terminal output", 949, 950, 1, 0},
	{"vis", "Control startup flags", 951, 962, 1, 0},
	{"mpt", "Control vi prompts", 963, 973, 1, 0},
	{"order", "Reorder characters based on rules defined in conf.c", 974, 976, 1, 0},
	{"shape", "Perform Arabic script letter shaping", 976, 978, 1, 0},
	{"pac", "Print autocomplete suggestions on the fly", 978, 979, 1, 0},
	{"ts", "Number of spaces used to represent a tab", 979, 980, 1, 0},
	{"td", "Current text direction context", 980, 986, 1, 0},
	{"pr", "Print register", 987, 1003, 1, 0},
	{"fr", "Find register", 1004, 1016, 1, 0},
	{"rr", "Record register", 1017, 1030, 1, 0},
	{"lim", "Line length render limit", 1031, 1046, 1, 0},
	{"seq", "Control Undo/Redo", 1047, 1059, 1, 0},
	{"left", "Control horizontal scroll", 1060, 1065, 1, 0},
	{"err", "Control ex errors", 1066, 1078, 1, 0},
};
